### ISSUE TITLE
`thread 'main' panicked at 'Unexpected state TimedOut(TimedOutDepositState)',` during `fedimint-cli await-deposit`

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/fedimint#2917]
Commands run on 0f6096b3bb5961a1697e4591b4d2526629b13c2d using `just mprocs`
```shell
mbp:fedimint ethantuttle$ bc sendtoaddress bcrt1qj2c54alr09eafkpmwp8ul4emvyldfct3x9sshsqxl9gy58nn3eeseh8za7 2.5342978
d559e23666e3101e0d07a3854360d2a0f44511057c847a533b285dfd1884ce9c
mbp:fedimint ethantuttle$ bc gettransaction d559e23666e3101e0d07a3854360d2a0f44511057c847a533b285dfd1884ce9c
{
  "amount": -2.53429780,
  "fee": -0.00006160,
  "confirmations": 0,
  "trusted": true,
  "txid": "d559e23666e3101e0d07a3854360d2a0f44511057c847a533b285dfd1884ce9c",
  "wtxid": "b7ecd5998df75de646ff1cbdadca91fa32ce0197af6ddf34c33996ba1b5a3e26",
  "walletconflicts": [
  ],
  "time": 1691458441,
  "timereceived": 1691458441,
  "bip125-replaceable": "yes",
  "details": [
    {
      "address": "bcrt1qj2c54alr09eafkpmwp8ul4emvyldfct3x9sshsqxl9gy58nn3eeseh8za7",
      "category": "send",
      "amount": -2.53429780,
      "vout": 0,
      "fee": -0.00006160,
      "abandoned": false
    }
  ],
  "hex": "0200000000010189d8f41c3190b800e96e0730a41d40ad9a48135160343203846eaef21ba5ebdc0100000000fdffffff0214081b0f0000000022002092b14af7e37973d4d83b704fcfd73b613ed4e17131610bc006f9504a1e738e739ccdf314010000002251205d9240cb2e3727f82626156157274390fa745d850b03d2c8a44cd2ba6d05fddd01403b6402170fa800e713a1e029d10ce477b9443a632bb1996cc30d343c2cce0902a69a4e5195358f3285a5810aed5ef0abfe784a77a6452b2887d0d876a918ccbf07010000"
}

mbp:fedimint ethantuttle$ fedimint-cli await-deposit dd0c61ff8d99f75c57cfb8226beb62f4feb35ecbc966c8d639749bacb54bc8e4
2023-08-08T01:38:02.397919Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-08-08T01:38:02.401396Z  INFO fedimint_cli::client: Update: WaitingForTransaction
thread 'main' panicked at 'Unexpected state TimedOut(TimedOutDepositState)', modules/fedimint-wallet-client/src/lib.rs:216:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-08-08T01:38:02.403693Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-08-08T01:38:02.403732Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
mbp:fedimint ethantuttle$ fedimint-cli await-deposit dd0c61ff8d99f75c57cfb8226beb62f4feb35ecbc966c8d639749bacb54bc8e4
2023-08-08T01:38:26.323243Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-08-08T01:38:26.323650Z  INFO fedimint_cli::client: Update: WaitingForTransaction
thread 'main' panicked at 'Unexpected state TimedOut(TimedOutDepositState)', modules/fedimint-wallet-client/src/lib.rs:216:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-08-08T01:38:26.323809Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-08-08T01:38:26.323868Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
```

**Comment by EthnTuttle** [comment]
I thought it was perhaps because I needed to mine a block, but that did not resolve the issue:
```
mbp:fedimint ethantuttle$ bc -regtest -generate 1
{
  "address": "bcrt1qaxctmetpk4f0rzuwsjq20uhvw4marxj3kttmms",
  "blocks": [
    "3c8ec38780342384013949a0fb36107166fb0d4aa8fed6db10cdc859381a3715"
  ]
}
mbp:fedimint ethantuttle$ fedimint-cli await-deposit dd0c61ff8d99f75c57cfb8226beb62f4feb35ecbc966c8d639749bacb54bc8e4
2023-08-08T01:45:08.756375Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-08-08T01:45:08.757102Z  INFO fedimint_cli::client: Update: WaitingForTransaction
thread 'main' panicked at 'Unexpected state TimedOut(TimedOutDepositState)', modules/fedimint-wallet-client/src/lib.rs:216:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-08-08T01:45:08.759182Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-08-08T01:45:08.759217Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
mbp:fedimint ethantuttle$ bc gettransaction d559e23666e3101e0d07a3854360d2a0f44511057c847a533b285dfd1884ce9c
{
  "amount": -2.53429780,
  "fee": -0.00006160,
  "confirmations": 1,
  "blockhash": "3c8ec38780342384013949a0fb36107166fb0d4aa8fed6db10cdc859381a3715",
  "blockheight": 264,
  "blockindex": 1,
  "blocktime": 1691459092,
  "txid": "d559e23666e3101e0d07a3854360d2a0f44511057c847a533b285dfd1884ce9c",
  "wtxid": "b7ecd5998df75de646ff1cbdadca91fa32ce0197af6ddf34c33996ba1b5a3e26",
  "walletconflicts": [
  ],
  "time": 1691458441,
  "timereceived": 1691458441,
  "bip125-replaceable": "no",
  "details": [
    {
      "address": "bcrt1qj2c54alr09eafkpmwp8ul4emvyldfct3x9sshsqxl9gy58nn3eeseh8za7",
      "category": "send",
      "amount": -2.53429780,
      "vout": 0,
      "fee": -0.00006160,
      "abandoned": false
    }
  ],
  "hex": "0200000000010189d8f41c3190b800e96e0730a41d40ad9a48135160343203846eaef21ba5ebdc0100000000fdffffff0214081b0f0000000022002092b14af7e37973d4d83b704fcfd73b613ed4e17131610bc006f9504a1e738e739ccdf314010000002251205d9240cb2e3727f82626156157274390fa745d850b03d2c8a44cd2ba6d05fddd01403b6402170fa800e713a1e029d10ce477b9443a632bb1996cc30d343c2cce0902a69a4e5195358f3285a5810aed5ef0abfe784a77a6452b2887d0d876a918ccbf07010000"
}
```

**Comment by EthnTuttle** [comment]
Restarted `mprocs` and working fine now.

**Comment by elsirion** [comment]
You don't happen to still have the old client DB (the one that failed) somewhere? That would help a lot with debugging since the new client keeps a log of its state transitions.

**Comment by EthnTuttle** [comment]
I copied out the directory from `/tmp` that I believe would have the error. Which file within should I extract the logs from?
Scanning through it looks like probably something within the `cfg/client.db` directory?

**Comment by justinmoon** [comment]
> I copied out the directory from `/tmp` that I believe would have the error. Which file within should I extract the logs from? Scanning through it looks like probably something within the `cfg/client.db` directory?

I think Eric probably wants that whole `cfg/client.db` folder.

**Comment by justinmoon** [comment]
Is this still actionable?

**Comment by elsirion** [comment]
Fixed by https://github.com/fedimint/fedimint/pull/3117 when fixing the duplicated #2993 of this issue.
