### ISSUE TITLE
Modules can't write to `0x50` database key

### ISSUE THREAD

**Issue by toyota-corolla0** [fedimint/fedimint#3481]
When ```PeersProposedTimestamp``` is set to ```0x50``` as shown below I get the error below. Changing it to other values fixes the issue. I am using a prefix to get all entries in ```PeersProposedTimestamp```. My project is forked from [fedimint-custom-module-example](https://github.com/fedimint/fedimint-custom-modules-example).

Some other values that I have set ```PeersProposedTimestamp``` to include ```0x51```, ```0x55```, ```0x80```, and ```0xa0```. All of these other values work fine.

### DBKeyPrefix:
```rust
/// Namespaces DB keys for this module
#[repr(u8)]
#[derive(Clone, EnumIter, Debug)]
pub enum DbKeyPrefix {
    /// ----- 00-1f reserved for struct storage -----

    /// [PredictionMarketsOutput] [OutPoint] to [PredictionMarketsOutputOutcome]
    Outcome = 0x00,

    /// [NewMarket] [OutPoint] to [Market]
    Market = 0x01,

    /// Owner's [XOnlyPublicKey] to [Order]
    Order = 0x02,

    /// ----- 20-3f reserved for market operation -----

    /// Used to produce time priority for new orders
    ///
    /// Market's [OutPoint] to [TimeOrdering]
    NextOrderTimeOrdering = 0x20,

    /// Used for payouts
    ///
    /// (Market's [OutPoint], Order's [OutPoint]) to ()
    OrdersByMarket = 0x21,

    /// Used to implement orderbook. Only holds active orders.
    ///
    /// Amount is (contract_price - price of order) for buys
    /// Amount is (price of order) for sells
    ///
    /// (Market's [OutPoint], [OutcomeSize], [Side], [Amount], [TimeOrdering]) to (Order's [XOnlyPublicKey])
    OrderPriceTimePriority = 0x22,

    /// ----- 40-4f reserved for api lookup indexes -----

    /// Indexes outcome control keys to the markets they belong to
    /// Used by client for data recovery in case of data loss
    ///
    /// ([XOnlyPublicKey], Market's [OutPoint]) to ()
    OutcomeControlMarkets = 0x40,

    /// ----- 50-5f reserved for consensus items -----
    
    /// Used for creating an agreed upon timestamp for order
    /// matching information (candlestick data)
    /// 
    /// [PeerId] to [UnixTimestamp] 
    PeersProposedTimestamp = 0x50,
}
```

### db record
```rust
// PeersProposedTimestamp
#[derive(Debug, Clone, Encodable, Decodable, Eq, PartialEq, Hash, Serialize)]
pub struct PeersProposedTimestampKey {
    pub peer_id: PeerId,
}

#[derive(Debug, Encodable, Decodable)]
pub struct PeersProposedTimestampPrefixAll;

impl_db_record!(
    key = PeersProposedTimestampKey,
    value = UnixTimestamp,
    db_prefix = DbKeyPrefix::PeersProposedTimestamp,
);

impl_db_lookup!(
    key = PeersProposedTimestampKey,
    query_prefix = PeersProposedTimestampPrefixAll
);
```

### Error
```
thread 'main' panicked at 'Unrecoverable error reading the DatabaseKey: Other(BigSize decoding error: ShortRead

Stack backtrace:
   0: fedimint_core::encoding::DecodeError::from_err
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/encoding/mod.rs:562:21
   1: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
   2: core::result::Result<T,E>::map_err
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:828:27
   3: <u16 as fedimint_core::encoding::Decodable>::consensus_decode
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/encoding/mod.rs:207:30
   4: <fedimint_core::PeerId as fedimint_core::encoding::Decodable>::consensus_decode
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/lib.rs:72:5
   5: <fedimint_prediction_markets_server::db::PeersProposedTimestampKey as fedimint_core::encoding::Decodable>::consensus_decode
             at ./fedimint-prediction-markets-server/src/db.rs:246:35
   6: <T as fedimint_core::db::DatabaseKey>::from_bytes
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/db/mod.rs:1323:9
   7: fedimint_core::db::ModuleDatabaseTransaction<T>::find_by_prefix::{{closure}}::{{closure}}::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/db/mod.rs:741:27
   8: <T as futures_util::fns::FnMut1<A>>::call_mut
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/fns.rs:28:9
   9: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:59:33
  10: core::option::Option<T>::map
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/option.rs:1075:29
  11: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:59:21
  12: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:58:26
  13: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/collect.rs:50:26
  14: fedimint_prediction_markets_server::PredictionMarkets::get_consensus_timestamp::{{closure}}
             at ./fedimint-prediction-markets-server/src/lib.rs:1180:14
  15: <fedimint_prediction_markets_server::PredictionMarkets as fedimint_core::module::ServerModule>::consensus_proposal::{{closure}}
             at ./fedimint-prediction-markets-server/src/lib.rs:311:70
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/future/future.rs:125:9
  17: <T as fedimint_core::core::server::IServerModule>::consensus_proposal::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/core/server.rs:164:14
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/future/future.rs:125:9
  19: fedimint_server::consensus::FedimintConsensus::get_consensus_proposal::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-server/src/consensus/mod.rs:468:18
  20: fedimint_server::consensus::server::ConsensusServer::process_events_then_propose::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-server/src/consensus/server.rs:489:74
  21: fedimint_server::consensus::server::ConsensusServer::run_consensus_epoch::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-server/src/consensus/server.rs:461:76
  22: fedimint_server::consensus::server::ConsensusServer::run_consensus::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-server/src/consensus/server.rs:279:69
  23: fedimint_server::FedimintServer::run::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-server/src/lib.rs:100:56
  24: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
  25: fedimintd::fedimintd::run::{{closure}}::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/join_mod.rs:95:13
  26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/poll_fn.rs:56:9
  27: fedimintd::fedimintd::run::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimintd/src/fedimintd.rs:281:48
  28: fedimintd::fedimintd::Fedimintd::run::{{closure}}::{{closure}}::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimintd/src/fedimintd.rs:186:18
  29: fedimint_core::task::TaskGroup::spawn_local::{{closure}}::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/task.rs:217:23
  30: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  31: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
      tokio::runtime::task::core::Core<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  32: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic/unwind_safe.rs:271:9
  34: std::panicking::try::do_call
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  35: __rust_try
  36: std::panicking::try
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  37: std::panic::catch_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  38: tokio::runtime::task::harness::poll_future
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  39: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  40: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  41: tokio::runtime::task::raw::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  42: tokio::runtime::task::raw::RawTask::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  43: tokio::runtime::task::LocalNotified<S>::run
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  44: tokio::task::local::LocalSet::tick::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/local.rs:617:63
  45: tokio::runtime::coop::with_budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
      tokio::task::local::LocalSet::tick
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/local.rs:617:31
  46: <tokio::task::local::LocalSet as core::future::future::Future>::poll::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/local.rs:830:25
  47: tokio::task::local::LocalSet::with::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/local.rs:686:13
  48: std::thread::local::LocalKey<T>::try_with
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/local.rs:270:16
  49: std::thread::local::LocalKey<T>::with
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/local.rs:246:9
  50: tokio::task::local::LocalSet::with
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/local.rs:669:9
  51: <tokio::task::local::LocalSet as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/local.rs:830:12
  52: fedimintd::fedimintd::Fedimintd::run::{{closure}}::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/macros/select.rs:524:49
  53: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/future/poll_fn.rs:58:9
  54: fedimintd::fedimintd::Fedimintd::run::{{closure}}
             at /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimintd/src/fedimintd.rs:208:9
  55: fedimintd::main::{{closure}}
             at ./fedimintd/src/fedimintd.rs:14:10
  56: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  57: tokio::runtime::coop::with_budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
      tokio::runtime::park::CachedParkThread::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  58: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  59: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  60: tokio::runtime::context::runtime::enter_runtime
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  61: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  62: tokio::runtime::runtime::Runtime::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  63: fedimintd::main
             at ./fedimintd/src/fedimintd.rs:5:5
  64: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  65: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:135:18
  66: std::rt::lang_start::{{closure}}
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:166:18
  67: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:20
  68: std::rt::lang_start
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:165:17
  69: main
  70: __libc_start_call_main
  71: __libc_start_main@@GLIBC_2.34
  72: _start)', /home/user/.cargo/git/checkouts/fedimint-52096cb7a051b8d1/6361d2e/fedimint-core/src/db/mod.rs:742:22
```

**Comment by Kodylow** [comment]
just talked about this in dev call, @elsirion thinks it's an issue outside of the bigsize encoding probably happening in the db, could you link to your repo so we can try to replicate?

**Comment by elsirion** [comment]
The problem is that we save the module's database version under this key. This might have been an oversight stemming from wanting to use the same `apply_migrations` function for modules as for fedimint itself.

In the case of modules it's just run on a module database transaction that can only write inside the module's namespace. But since it's still using the same database transaction to persist the DB version it now writes the DB version key (`0x50`) into the module DB.

https://github.com/fedimint/fedimint/blob/dc2fb79eded1f0aeaa47a9cee867b8cc0065bcc4/fedimint-core/src/db/mod.rs#L1614-L1615

I see two approaches:
* **easy:** change the version key to something more "out of the way" like `0xff` and document that e.g. the entire`0xf*` range is off-limits
* **harder but cleaner:** save module DB versions outside the module's DB partition since the migrations are driven from the outside anyway.

**Comment by dpc** [comment]
harder but cleaner is the way; could be a one-off hacky job migration to move it (just have some key that remember if you ran some one-off piece of code moving these records where they should be), but it should be done.

**Comment by elsirion** [comment]
I think we could use the global DB migration, it should have access to the module namespaces. Just read keys `[0xff, m, 0x50]` for all `m` and create a new key that represents module DB versions, maybe `[0x51, m]`.

**Comment by m1sterc001guy** [comment]
Ack. Yes, should have used the global namespace for this. This should be a doable migration

**Comment by dpc** [comment]
I need to verify, but just not to forget and document it: because of https://github.com/fedimint/fedimint/pull/4585 , the version field might not have always(ever?) been correctly migrated.
