### ISSUE TITLE
`fedimint-cli config` crashes if there are unknown modules

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3548]
This is a connection string to a mutinynet federation running 0.1 release containing 2 custom modules: `fed115fjxjp793mdynuq78ju724wxelmhj336pqw845d8s4a5jfm75a3d8hc8hwmg4nmskmrpkzw5cqk6yqpfwaehxw309askcurgvyhx6at5d9h8jmn9wsknqv3wv3jhvtnxv4jxjcn5vvhxxmmd97a5ttq64kahlwtahn07zr64k2c`

If you run `fedimint-cli config` after joining this federation, you get the following:

```
2023-11-07T20:59:30.109474Z  INFO fedimint_client: Detected configuration for unsupported module id: 3, kind: fedi-social
2023-11-07T20:59:30.109554Z  INFO fedimint_client: Detected configuration for unsupported module id: 4, kind: stability_pool
2023-11-07T20:59:30.162592Z  WARN fedimint_client: Module kind fedi-social of instance 3 not found in module gens, skipping
2023-11-07T20:59:30.162613Z  WARN fedimint_client: Module kind stability_pool of instance 4 not found in module gens, skipping
2023-11-07T20:59:30.163068Z  INFO fedimint_client::sm::executor: Starting state machine executor task
thread 'main' panicked at /Users/justin/work/fedimint/fedimint-core/src/encoding/mod.rs:734:17:
Expected decoded value. Possibly `redecode_raw` call is missing.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-07T20:59:30.164639Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-11-07T20:59:30.164728Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
```

**Comment by justinmoon** [comment]
Right after observing this, I tried to spend some ecash and observed this:

```
$ cargo run --bin fedimint-cli -- --data-dir federations/mutinynet-02 spend 1
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/fedimint-cli --data-dir federations/mutinynet-02 spend 1`
2023-11-07T21:03:15.559629Z  INFO fedimint_client: Detected configuration for unsupported module id: 3, kind: fedi-social
2023-11-07T21:03:15.559700Z  INFO fedimint_client: Detected configuration for unsupported module id: 4, kind: stability_pool
2023-11-07T21:03:15.615263Z  WARN fedimint_client: Module kind fedi-social of instance 3 not found in module gens, skipping
2023-11-07T21:03:15.615298Z  WARN fedimint_client: Module kind stability_pool of instance 4 not found in module gens, skipping
2023-11-07T21:03:15.615915Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-11-07T21:03:15.617057Z ERROR fedimint_core::db: error=Other decoding error: Error decoding blind message
thread 'main' panicked at /Users/justin/work/fedimint/fedimint-core/src/db/mod.rs:2401:18:
Unrecoverable decoding DatabaseValue: key: 20fe0200000072d9b5c686fce6fbd3d5d50b8c2d07442ead5e7a8f40465b0dcd7db8cb066c17

Caused by:
    Other decoding error: Error decoding blind message
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-07T21:03:15.617786Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-11-07T21:03:15.617878Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
```

**Comment by justinmoon** [comment]
I just tried this again on master to see if it's still a problem, and I got a slightly different error message. That database key looks a little suspect to me because I know we used to use a similar-looking key for backup & recovery state machine:

```
2024-02-05T13:00:38.489360Z  WARN fedimint_client: Detected configuration for unsupported module id: 3, kind: fedi-social
2024-02-05T13:00:38.489385Z  WARN fedimint_client: Detected configuration for unsupported module id: 4, kind: stability_pool
2024-02-05T13:00:38.489416Z  WARN fedimint_client: Client missing ClientRequiresRecovery: assuming complete
2024-02-05T13:00:38.496854Z  WARN fedimint_client: Module kind fedi-social of instance 3 not found in module gens, skipping
2024-02-05T13:00:38.496880Z  WARN fedimint_client: Module kind stability_pool of instance 4 not found in module gens, skipping
thread 'tokio-runtime-worker' panicked at /Users/justin/work/fedimint/fedimint-core/src/db/mod.rs:970:26:
Unrecoverable error reading DatabaseKey: key: a101010101010101010101010101010101010101010101010101010101010101010103fe00039ad7010101010101010101010101010101010101010101010101-236287

Caused by:
    Other decoding error: Invalid enum variant 3 while decoding MintClientStateMachines
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /Users/justin/work/fedimint/fedimint-core/src/encoding/mod.rs:897:17:
Expected decoded value. Possibly `redecode_raw` call is missing.
2024-02-05T13:00:38.498411Z  WARN fedimint_client::sm::executor: Failed to send shutdown signal to executor, already dead?
2024-02-05T13:00:38.498424Z ERROR fedimint_client: Error while awaiting client shutdown confirmation
```

**Comment by elsirion** [comment]
@dpc did we remove the recovery SM completely? This would be problematic for any client that recovered in the past as it would still have the state transition log.

Imo we should leave the enum variant in and just delete all state transitions. That way ongoing recoveries during upgrade get bricked (ok imo) while clients that recovered in the past keep working.

**Comment by elsirion** [comment]
@elsirion check if still a problem

**Comment by justinmoon** [comment]
@dpc did [#4399](https://github.com/fedimint/fedimint/pull/4399) fix this?
