### ISSUE TITLE
Panics under load test

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#3553]
On v0.1:
```
2023-11-08T03:31:23.183591Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-11-08T03:31:23.195708Z  INFO fedimint_load_test_tool: Current balance of 222080 msat already covers the minimum required of 1024 msat
2023-11-08T03:31:23.195726Z  INFO fedimint_load_test_tool: Reminting notes of denomination 1024 msat for 1 users, 1 notes per user (this may take a while if the number of users/notes is high)
2023-11-08T03:31:23.223967Z  WARN db: Database commit failed in an autocommit block curr_attempts=1
thread 'main' panicked at 'Unrecoverable error occurred while committing to the database.: Resource busy: ', /home/master/p/fedimint/fedimint-core/src/db/mod.rs:1120:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-08T03:31:24.906040Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-11-08T03:31:24.906285Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
66
2023-11-08T03:31:27.746851Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-11-08T03:31:27.759267Z  INFO fedimint_load_test_tool: Current balance of 223104 msat already covers the minimum required of 1024 msat
2023-11-08T03:31:27.759287Z  INFO fedimint_load_test_tool: Reminting notes of denomination 1024 msat for 1 users, 1 notes per user (this may take a while if the number of users/notes is high)
2023-11-08T03:31:28.798839Z  WARN db: DatabaseTransaction has writes and has not called commit.
2023-11-08T03:31:28.798883Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
thread 'tokio-runtime-worker' panicked at 'Can only fail if additional funding is needed: State already exists in database!', fedimint-client/src/lib.rs:399:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-08T03:31:28.812763Z  WARN db: DatabaseTransaction has writes and has not called commit.
2023-11-08T03:31:28.812909Z ERROR fedimint_client: Error while awaiting client shutdown confirmation
Error: Tx submission rejected: Federation rpc error {general => Received errors from 2 peers: peer-0: Rpc error: ErrorObject { code: ServerError(400), message: "One of the supplied notes was already spent previously", data: None }, peer-1: Rpc error: ErrorObject { code: ServerError(400), message: "One of the supplied notes was already spent previously", data: None }), 0 => Rpc error: ErrorObject { code: ServerError(400), message: "One of the supplied notes was already spent previously", data: None })1 => Rpc error: ErrorObject { code: ServerError(400), message: "One of the supplied notes was already spent previously", data: None }), }
67
2023-11-08T03:31:31.623447Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-11-08T03:31:31.635579Z  INFO fedimint_load_test_tool: Current balance of 223104 msat already covers the minimum required of 1024 msat
2023-11-08T03:31:31.635596Z  INFO fedimint_load_test_tool: Reminting notes of denomination 1024 msat for 1 users, 1 notes per user (this may take a while if the number of users/notes is high)
thread 'tokio-runtime-worker' panicked at 'Can only fail if additional funding is needed: State already exists in database!', fedimint-client/src/lib.rs:399:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-08T03:31:31.644763Z  WARN db: DatabaseTransaction has writes and has not called commit.
```

**Comment by douglaz** [comment]
It seems one of this errors still happens on AlephBFT:
https://github.com/fedimint/fedimint/issues/3639

**Comment by justinmoon** [comment]
dev call: this one is harder to reproduce, still an issue.

**Comment by bradleystachurski** [comment]
CI has been stable for a while now and we haven't observed this, so we can close.
