### ISSUE TITLE
[RC5] "The gateway is disconnected" on new federation setups

### ISSUE THREAD

**Issue by TonyGiorgio** [fedimint/fedimint#3852]
I'm using rc5 for the fedimint docker images and rc4 for the fedimintui docker images. 

Whenever I go through a new federation setup (using the mutiny tls scripts), I run into something that I believe might be related to this recent issue (https://github.com/fedimint/fedimint/issues/3806) & PR (https://github.com/fedimint/fedimint/pull/3833)

I was using RC2 before when I had that previous issue with a gateway that wouldn't connect to LND upon init, but restarting the docker images would fix the problem. However now a `docker compose restart` doesn't fix the problem. Here are the logs after a restart. 

```
fedimint-user@localhost:~/fedimint/docker$ docker compose logs -f gatewayd
docker-gatewayd-1  | 2023-12-06T04:57:20.009511Z  INFO ln_gateway: Starting gatewayd (version: 24113a64b270bf2ecb49b8f4554ba975025711db)
docker-gatewayd-1  | 2023-12-06T04:57:20.016193Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T04:57:20.018245Z  INFO ln_gateway: Successfully started webserver
docker-gatewayd-1  | 2023-12-06T04:57:20.025080Z ERROR ln_gateway: Disconnected from Lightning Node. Waiting 5 seconds and trying again
docker-gatewayd-1  | 2023-12-06T04:57:25.026398Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T04:57:25.086815Z ERROR ln_gateway: Disconnected from Lightning Node. Waiting 5 seconds and trying again
docker-gatewayd-1  | 2023-12-06T04:57:30.087182Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T04:57:30.134849Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T04:57:30.134869Z  INFO ln_gateway: Established HTLC stream
docker-gatewayd-1  | 2023-12-06T04:57:30.139715Z  WARN ln_gateway: Lightning node does not match previously configured gateway network : (Regtest)
docker-gatewayd-1  | 2023-12-06T04:57:30.139726Z  INFO ln_gateway: Changing gateway network to match lightning node network : (Signet)
docker-gatewayd-1  | 2023-12-06T04:57:30.139737Z  INFO task: Waiting for task to finish task=LND HTLC Subscription
docker-gatewayd-1  | 2023-12-06T04:57:30.139794Z  INFO ln_gateway::lnd: LND HTLC Subscription received shutdown signal while trying to intercept HTLC stream, exiting...
docker-gatewayd-1  | 2023-12-06T04:57:30.139872Z  INFO task: Task finished task=LND HTLC Subscription
docker-gatewayd-1  | thread 'tokio-runtime-worker' panicked at /build/source/gateway/ln-gateway/src/lib.rs:485:58:
docker-gatewayd-1  | Failed to set gateway configuration: Disconnected
docker-gatewayd-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
docker-gatewayd-1  | 2023-12-06T05:08:48.861128Z ERROR connect_fed: ln_gateway::rpc::rpc_server: error=The gateway is disconnected
docker-gatewayd-1  | 2023-12-06T05:09:36.418112Z ERROR connect_fed: ln_gateway::rpc::rpc_server: error=The gateway is disconnected
docker-gatewayd-1  | 2023-12-06T05:15:00.483351Z  INFO task: signal received, starting graceful shutdown
docker-gatewayd-1  | 2023-12-06T05:15:00.483378Z  INFO gatewayd: Gatewayd exiting...
docker-gatewayd-1  | 2023-12-06T05:15:37.811789Z  INFO ln_gateway: Starting gatewayd (version: 24113a64b270bf2ecb49b8f4554ba975025711db)
docker-gatewayd-1  | 2023-12-06T05:15:37.812872Z  INFO ln_gateway: Successfully started webserver
docker-gatewayd-1  | 2023-12-06T05:15:37.812960Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T05:15:37.819920Z ERROR ln_gateway: Disconnected from Lightning Node. Waiting 5 seconds and trying again
docker-gatewayd-1  | 2023-12-06T05:15:42.821525Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T05:15:42.867734Z ERROR ln_gateway: Disconnected from Lightning Node. Waiting 5 seconds and trying again
docker-gatewayd-1  | 2023-12-06T05:15:47.868020Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T05:15:47.918089Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1  |  address: https://lnd:10009,
docker-gatewayd-1  |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1  |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1  | 2023-12-06T05:15:47.918115Z  INFO ln_gateway: Established HTLC stream
docker-gatewayd-1  | 2023-12-06T05:15:47.921928Z  WARN ln_gateway: Lightning node does not match previously configured gateway network : (Regtest)
docker-gatewayd-1  | 2023-12-06T05:15:47.921939Z  INFO ln_gateway: Changing gateway network to match lightning node network : (Signet)
docker-gatewayd-1  | 2023-12-06T05:15:47.921951Z  INFO task: Waiting for task to finish task=LND HTLC Subscription
docker-gatewayd-1  | 2023-12-06T05:15:47.921962Z  INFO ln_gateway::lnd: LND HTLC Subscription received shutdown signal while trying to intercept HTLC stream, exiting...
docker-gatewayd-1  | 2023-12-06T05:15:47.921982Z  INFO task: Task finished task=LND HTLC Subscription
docker-gatewayd-1  | thread 'tokio-runtime-worker' panicked at /build/source/gateway/ln-gateway/src/lib.rs:485:58:
docker-gatewayd-1  | Failed to set gateway configuration: Disconnected
docker-gatewayd-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by elsirion** [comment]
Easiest fix: just set the network via CLI arg to `gatewayd` (idk how easy that is to patch into the docker file @Kodylow). It feels to me like there's way too much "cleverness" in that gateway startup routine: one can either set the network or it defaults to regtest, but if it doesn't match we just change it to match :laughing: 

How it likely should be: if one is set validate against the LN node and fail on mismatch. If none is set use the network from the LN node, fail if not connected (on startup we can assume the LN node being present).

As a quick fix without touching docker files I could imagine just removing the check against being in disconnected state: 

https://github.com/fedimint/fedimint/blob/b7a70611896044e7973f58d741afd4c1bcb86427/gateway/ln-gateway/src/lib.rs#L917-L919

But I haven't worked on the GW in a long time, so would refer to @okjodom, @m1sterc001guy and @douglaz for if this is a sane idea.
