### ISSUE TITLE
Restart federation flaky?

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#4099]
Recently saw this test failure after the tests had already successfully run

```
fedimint-workspace-lcov-ci> 2024-01-22T19:41:15.343480Z  INFO net::api: Starting api on ws://127.0.0.1:25031
fedimint-workspace-lcov-ci> 2024-01-22T19:41:15.343510Z  INFO consensus: Starting config gen
fedimint-workspace-lcov-ci> 2024-01-22T19:41:15.343601Z  INFO net::peer::dkg: Created new config gen Api
fedimint-workspace-lcov-ci> 2024-01-22T19:41:15.343872Z  INFO net::api: Starting api on ws://127.0.0.1:25033
fedimint-workspace-lcov-ci> 2024-01-22T19:41:15.343892Z  INFO consensus: Starting config gen
fedimint-workspace-lcov-ci> 2024-01-22T19:41:15.343925Z  INFO net::peer::dkg: Created new config gen Api
fedimint-workspace-lcov-ci> 2024-01-22T19:41:16.342903Z  INFO test: Test retrying server status
fedimint-workspace-lcov-ci> 2024-01-22T19:41:16.345235Z  INFO net::peer::dkg: Set password for config gen
fedimint-workspace-lcov-ci> 2024-01-22T19:41:16.345542Z  WARN net::api: api request error path="set_password" error=ApiError { code: 400, message: "Expected to be in AwaitingPassword state" }
fedimint-workspace-lcov-ci> thread 'tokio-runtime-worker' panicked at fedimint-server/src/lib.rs:206:14:
fedimint-workspace-lcov-ci> Could not build API server: API name: config-gen
fedimint-workspace-lcov-ci> Caused by:
fedimint-workspace-lcov-ci>     0: Bind address: 127.0.0.1:25035
fedimint-workspace-lcov-ci>     1: Networking or low-level protocol error: Address already in use (os error 98)
fedimint-workspace-lcov-ci>     2: Address already in use (os error 98)
fedimint-workspace-lcov-ci> Stack backtrace:
fedimint-workspace-lcov-ci>    0: <core::result::Result<jsonrpsee_server::server::Server, jsonrpsee_core::error::Error> as anyhow::Context<jsonrpsee_server::server::Server, jsonrpsee_core::error::Error>>::context::<alloc::string::String>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/anyhow-1.0.75/src/context.rs:54:31
fedimint-workspace-lcov-ci>    1: {async_fn#0}<fedimint_server::config::api::ConfigGenApi>
fedimint-workspace-lcov-ci>              at ./src/lib.rs:201:22
fedimint-workspace-lcov-ci>    2: {async_fn#0}
fedimint-workspace-lcov-ci>              at ./src/lib.rs:147:90
fedimint-workspace-lcov-ci>    3: {async_fn#0}
fedimint-workspace-lcov-ci>              at ./src/lib.rs:91:14
fedimint-workspace-lcov-ci>    4: poll<fedimint_server::{impl#0}::run::{async_fn_env#0}>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/futures-util-0.3.29/src/future/maybe_done.rs:95:38
fedimint-workspace-lcov-ci>    5: poll<fedimint_server::{impl#0}::run::{async_fn_env#0}>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/futures-util-0.3.29/src/future/join_all.rs:142:24
fedimint-workspace-lcov-ci>    6: {async_block#0}
fedimint-workspace-lcov-ci>              at ./src/config/api.rs:1114:76
fedimint-workspace-lcov-ci>    7: poll<fedimint_server::config::api::tests::test_config_api::{async_block#0}::{async_block_env#0}>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tracing-0.1.40/src/instrument.rs:321:9
fedimint-workspace-lcov-ci>    8: {closure#0}<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{async_block#0}::{async_block_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/core.rs:328:17
fedimint-workspace-lcov-ci>    9: with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{async_block#0}::{async_block_env#0}>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{async_block#0}::{async_block_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/loom/std/unsafe_cell.rs:16:9
fedimint-workspace-lcov-ci>       poll<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{async_block#0}::{async_block_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/core.rs:317:13
fedimint-workspace-lcov-ci>   10: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{closure#0}::{closure#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:485:19
fedimint-workspace-lcov-ci>   11: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{closure#0}::{closure#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
fedimint-workspace-lcov-ci>   12: do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{async_block#0}::{async_block_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>, core::task::poll::Poll<()>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
fedimint-workspace-lcov-ci>   13: __rust_try
fedimint-workspace-lcov-ci>   14: try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{async_block#0}::{async_block_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
fedimint-workspace-lcov-ci>   15: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{closure#0}::{closure#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>, core::task::poll::Poll<()>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
fedimint-workspace-lcov-ci>   16: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{closure#0}::{closure#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:473:18
fedimint-workspace-lcov-ci>   17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{closure#0}::{closure#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:208:27
fedimint-workspace-lcov-ci>   18: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{closure#0}::{closure#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:153:15
fedimint-workspace-lcov-ci>   19: tokio::runtime::task::raw::poll::<tracing::instrument::Instrumented<fedimint_server::config::api::tests::test_config_api::{closure#0}::{closure#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/raw.rs:271:5
fedimint-workspace-lcov-ci>   20: run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/mod.rs:408:9
fedimint-workspace-lcov-ci>       {closure#0}
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:577:13
fedimint-workspace-lcov-ci>       with_budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/coop.rs:107:5
fedimint-workspace-lcov-ci>       budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/coop.rs:73:5
fedimint-workspace-lcov-ci>       run_task
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:576:9
fedimint-workspace-lcov-ci>   21: run
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
fedimint-workspace-lcov-ci>       {closure#0}
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
fedimint-workspace-lcov-ci>       set<tokio::runtime::scheduler::Context, tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}, ()>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/context/scoped.rs:40:9
fedimint-workspace-lcov-ci>   22: {closure#0}<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/context.rs:176:26
fedimint-workspace-lcov-ci>       try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}>, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:270:16
fedimint-workspace-lcov-ci>       with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}>, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:9
fedimint-workspace-lcov-ci>   23: tokio::runtime::context::set_scheduler::<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/context.rs:176:9
fedimint-workspace-lcov-ci>   24: {closure#0}
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
fedimint-workspace-lcov-ci>       enter_runtime<tokio::runtime::scheduler::multi_thread::worker::run::{closure_env#0}, ()>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/context/runtime.rs:65:16
fedimint-workspace-lcov-ci>   25: run
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
fedimint-workspace-lcov-ci>   26: {closure#0}
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
fedimint-workspace-lcov-ci>       poll<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}, ()>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/blocking/task.rs:42:21
fedimint-workspace-lcov-ci>       poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tracing-0.1.40/src/instrument.rs:321:9
fedimint-workspace-lcov-ci>   27: {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/core.rs:328:17
fedimint-workspace-lcov-ci>       with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/loom/std/unsafe_cell.rs:16:9
fedimint-workspace-lcov-ci>       poll<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/core.rs:317:13
fedimint-workspace-lcov-ci>   28: {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:485:19
fedimint-workspace-lcov-ci>       call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
fedimint-workspace-lcov-ci>       do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<()>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
fedimint-workspace-lcov-ci>       try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
fedimint-workspace-lcov-ci>   29: catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<()>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
fedimint-workspace-lcov-ci>       poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:473:18
fedimint-workspace-lcov-ci>   30: poll_inner<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:208:27
fedimint-workspace-lcov-ci>   31: poll<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/harness.rs:153:15
fedimint-workspace-lcov-ci>   32: run<tokio::runtime::blocking::schedule::BlockingSchedule>
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/task/mod.rs:445:9
fedimint-workspace-lcov-ci>   33: run
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/blocking/pool.rs:159:9
fedimint-workspace-lcov-ci>       run
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/blocking/pool.rs:513:17
fedimint-workspace-lcov-ci>   34: {closure#0}
fedimint-workspace-lcov-ci>              at /nix/store/8lmnvrgxpw04yglr9fq9gj8njp42vc0g-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.34.0/src/runtime/blocking/pool.rs:471:13
fedimint-workspace-lcov-ci>       __rust_begin_short_backtrace<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154:18
fedimint-workspace-lcov-ci>   35: {closure#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/mod.rs:529:17
fedimint-workspace-lcov-ci>       call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
fedimint-workspace-lcov-ci>       do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
fedimint-workspace-lcov-ci>       try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
fedimint-workspace-lcov-ci>       catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
fedimint-workspace-lcov-ci>       {closure#1}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/mod.rs:528:30
fedimint-workspace-lcov-ci>       call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>, ()>
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
fedimint-workspace-lcov-ci>   36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
fedimint-workspace-lcov-ci>       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
fedimint-workspace-lcov-ci>       std::sys::unix::thread::Thread::new::thread_start
fedimint-workspace-lcov-ci>              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108:17
fedimint-workspace-lcov-ci>   37: start_thread
fedimint-workspace-lcov-ci>   38: __GI___clone3
```

@okjodom there were some recent changes here right?

**Comment by okjodom** [comment]
ack. we introduced restart rpc and tests with #3669

**Comment by okjodom** [comment]
@m1sterc001guy could you link to the relevant CI run?

**Comment by m1sterc001guy** [comment]
https://github.com/fedimint/fedimint/actions/runs/7616433363/job/20743174870

**Comment by okjodom** [comment]
I'm kind of convinced this test flaked because of [config-gen server port allocation failure](https://github.com/fedimint/fedimint/actions/runs/7616433363/job/20743174870#step:6:2335). Why that could have happened in this CI run is unclear

**Comment by okjodom** [comment]
All attempts to reproduce locally were unsuccessful. So I think we wait and see if it reoccurs...
Tracking in #2825
