### ISSUE TITLE
Investigating `strip = "debug-symbols"`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4115]
Inspired by the https://kobzol.github.io/rust/cargo/2024/01/23/making-rust-binaries-smaller-by-default.html , I decided to try `strip = "debug-symbols"` which is to be a default kind-of (when `debug = 0`) in upcoming Rust. I decided to try it out.

#### Change

```
> git diff HEAD
diff --git a/Cargo.toml b/Cargo.toml
index e77e1a5bc9..9f6856bcb3 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -105,3 +105,4 @@ incremental = false

 [profile.release]
 debug = "line-tables-only"
+strip = "debuginfo"
diff --git a/fedimint-cli/src/lib.rs b/fedimint-cli/src/lib.rs
index 63d6892b8b..063ffa9876 100644
--- a/fedimint-cli/src/lib.rs
+++ b/fedimint-cli/src/lib.rs
@@ -501,6 +501,7 @@ impl FedimintCli {
     }

     pub async fn run(&mut self) {
+        panic!("at the disko");
         match self.handle_command(self.cli_args.clone()).await {
             Ok(output) => {
                 // ignore if there's anyone reading the stuff we're writing out
```

#### Before

```
> ls -alh target/release/fedimint-cli
-rwxr-xr-x 2 dpc dpc 58M Jan 24 00:03 target/release/fedimint-cli

> env RUST_BACKTRACE=1 target/release/fedimint-cli completion fish
thread 'main' panicked at /home/dpc/lab/fedimint.git/dev/fedimint-cli/src/lib.rs:504:9:
at the disko
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: {async_fn#0}
             at ./fedimint-cli/src/lib.rs:504:9
   3: {async_block#0}
             at ./fedimint-cli/src/main.rs:8:10
   4: poll<fedimint_cli::main::{async_block_env#0}>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
   5: {closure#0}<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/park.rs:282:63
   6: with_budget<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/coop.rs:107:5
   7: budget<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/coop.rs:73:5
   8: block_on<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/park.rs:282:31
   9: block_on<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context/blocking.rs:66:9
  10: {closure#0}<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  11: enter_runtime<tokio::runtime::scheduler::multi_thread::{impl#0}::block_on::{closure_env#0}<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>, core::result::Result<(), anyhow::Error>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context/runtime.rs:65:16
  12: block_on<tracing::instrument::Instrumented<fedimint_cli::main::{async_block_env#0}>>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  13: block_on<fedimint_cli::main::{async_block_env#0}>
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/runtime.rs:350:50
  14: main
             at ./fedimint-cli/src/main.rs:9:5
  15: call_once<fn() -> core::result::Result<(), anyhow::Error>, ()>
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

#### After

```
> ls -alh target/release/fedimint-cli
-rwxr-xr-x 2 dpc dpc 31M Jan 24 00:14 target/release/fedimint-cli


> ls -alh target/release/fedimint-cli
-rwxr-xr-x 2 dpc dpc 31M Jan 24 00:14 target/release/fedimint-cli
00:19:05 …lab/fedimint.git/dev  master:u/master [$!?] via 🦀 v1.73.0 ❄️
> env RUST_BACKTRACE=1 target/release/fedimint-cli completion fish
thread 'main' panicked at /home/dpc/lab/fedimint.git/dev/fedimint-cli/src/lib.rs:504:9:
at the disko
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   3: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
   4: tokio::runtime::context::runtime::enter_runtime
   5: tokio::runtime::runtime::Runtime::block_on
   6: fedimint_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

> env RUST_BACKTRACE=full target/release/fedimint-cli completion fish
thread 'main' panicked at /home/dpc/lab/fedimint.git/dev/fedimint-cli/src/lib.rs:504:9:
at the disko
stack backtrace:
   0:     0x564de965998c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
   1:     0x564de96868ac - core::fmt::write::hb8eaf5a8e45a738e
   2:     0x564de965541e - std::io::Write::write_fmt::h9663fe36b2ee08f9
   3:     0x564de9659774 - std::sys_common::backtrace::print::h1360e9450e4f922a
   4:     0x564de965ae23 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
   5:     0x564de965ab3c - std::panicking::default_hook::h6d75f5747cab6e8d
   6:     0x564de965b419 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
   7:     0x564de965b2d1 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
   8:     0x564de9659eb6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
   9:     0x564de965b062 - rust_begin_unwind
  10:     0x564de9683f73 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
  11:     0x564de89347ce - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h636568d2a7d25e97
  12:     0x564de893a1af - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h10fd5a417bfab518
  13:     0x564de8935a9d - tokio::runtime::context::runtime::enter_runtime::h16771fad8c580b80
  14:     0x564de893d694 - tokio::runtime::runtime::Runtime::block_on::h008b7a94cc809c0b
  15:     0x564de89389cb - fedimint_cli::main::hf61ac4ea3a1c4861
  16:     0x564de8939a13 - std::sys_common::backtrace::__rust_begin_short_backtrace::h514bdc7461da86f5
  17:     0x564de8939a2d - std::rt::lang_start::{{closure}}::h1b036e9c56b5023d
  18:     0x564de964f67b - std::rt::lang_start_internal::hc0b4e50f058f62ce
  19:     0x564de8938abc - main
  20:     0x7fc2d03a3fce - __libc_start_call_main
  21:     0x7fc2d03a4089 - __libc_start_main_impl
  22:     0x564de8931425 - _start
  23:                0x0 - <unknown>
```

#### Summary

58 - 31 = 27MB saved in a binary, but the stack trace gets limited (no line numbers).

**Comment by dpc** [comment]
Closing, because I'm not sure if this is actionable, but pikng @fedimint/infra to share the results.
