### ISSUE TITLE
`fedimintd` fails to catch up with peers

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4131]
```
Jan 25 03:04:27 charlie fedimintd-start[2026788]: thread 'main' panicked at fedimint-server-0.2.2-rc5/src/consensus/server.rs:448:97:
Jan 25 03:04:27 charlie fedimintd-start[2026788]: assertion failed: mid <= self.len()
Jan 25 03:04:27 charlie fedimintd-start[2026788]: stack backtrace:
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    0: rust_begin_unwind
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/std/src/panicking.rs:645:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    1: core::panicking::panic_fmt
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/core/src/panicking.rs:72:14
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    2: core::panicking::panic
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/core/src/panicking.rs:144:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    3: split_at<fedimint_core::session_outcome::AcceptedItem>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/core/src/slice/mod.rs:1867:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    4: {async_fn#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimint-server-0.2.2-rc5/src/consensus/server.rs:448:52
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    5: {async_fn#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimint-server-0.2.2-rc5/src/consensus/server.rs:399:14
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    6: {async_fn#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimint-server-0.2.2-rc5/src/consensus/server.rs:287:45
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    7: {async_fn#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimint-server-0.2.2-rc5/src/consensus/server.rs:217:45
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    8: {async_fn#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimint-server-0.2.2-rc5/src/lib.rs:103:56
Jan 25 03:04:28 charlie fedimintd-start[2026788]:    9: {async_fn#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimintd-0.2.2-rc5/src/fedimintd.rs:308:29
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   10: {async_block#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimintd-0.2.2-rc5/src/fedimintd.rs:207:18
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   11: {async_block#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimint-core-0.2.2-rc5/src/task.rs:226:23
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   12: poll<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tracing-0.1.37/src/instrument.rs:272:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   13: {closure#0}<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/core.rs:334:17
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   14: with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   15: poll<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/core.rs:323:13
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   16: {closure#0}<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/harness.rs:485:19
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   17: call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/core/src/panic/unwind_safe.rs:272:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   18: do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>>, core::task::poll::Poll<()>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/std/src/panicking.rs:552:40
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   19: try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/std/src/panicking.rs:516:19
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   20: catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>>, core::task::poll::Poll<()>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/std/src/panic.rs:142:14
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   21: poll_future<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/harness.rs:473:18
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   22: poll_inner<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/harness.rs:208:27
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   23: poll<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/harness.rs:153:15
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   24: poll<tracing::instrument::Instrumented<fedimint_core::task::{impl#2}::spawn_local::{async_fn#0}::{async_block_env#0}<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure#0}::{async_block_env#0}, &str, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#0}>>, alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/raw.rs:276:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   25: poll
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/raw.rs:200:18
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   26: run<alloc::sync::Arc<tokio::task::local::Shared, alloc::alloc::Global>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/task/mod.rs:400:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   27: {closure#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/task/local.rs:617:68
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   28: with_budget<(), tokio::task::local::{impl#2}::tick::{closure_env#0}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/coop.rs:107:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   29: budget<(), tokio::task::local::{impl#2}::tick::{closure_env#0}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/coop.rs:73:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   30: tick
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/task/local.rs:617:31
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   31: {closure#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/task/local.rs:830:25
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   32: {closure#0}<bool, tokio::task::local::{impl#4}::poll::{closure_env#0}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/task/local.rs:686:13
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   33: try_with<tokio::task::local::LocalData, tokio::task::local::{impl#2}::with::{closure_env#0}<bool, tokio::task::local::{impl#4}::poll::{closure_env#0}>, bool>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/std/src/thread/local.rs:284:16
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   34: with<tokio::task::local::LocalData, tokio::task::local::{impl#2}::with::{closure_env#0}<bool, tokio::task::local::{impl#4}::poll::{closure_env#0}>, bool>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/std/src/thread/local.rs:260:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   35: with<bool, tokio::task::local::{impl#4}::poll::{closure_env#0}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/task/local.rs:669:17
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   36: poll
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/task/local.rs:830:12
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   37: {closure#2}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/macros/select.rs:524:49
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   38: poll<fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::__tokio_select_util::Out<(), ()>, fedimintd::fedimintd::{impl#0}::run::{async_fn#0}::{closure_env#2}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/future/poll_fn.rs:58:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   39: {async_fn#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimintd-0.2.2-rc5/src/fedimintd.rs:229:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   40: {async_block#0}
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimintd/src/main.rs:50:21
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   41: poll<fedimintd::main::{async_block_env#0}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tracing-0.1.37/src/instrument.rs:272:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   42: {closure#0}<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/park.rs:282:63
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   43: with_budget<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/coop.rs:107:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   44: budget<core::task::poll::Poll<core::result::Result<(), anyhow::Error>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/coop.rs:73:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   45: block_on<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/park.rs:282:31
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   46: block_on<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/context/blocking.rs:66:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   47: {closure#0}<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   48: enter_runtime<tokio::runtime::scheduler::multi_thread::{impl#0}::block_on::{closure_env#0}<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>, core::result::Result<(), anyhow::Error>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/context/runtime.rs:65:16
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   49: block_on<tracing::instrument::Instrumented<fedimintd::main::{async_block_env#0}>>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   50: block_on<fedimintd::main::{async_block_env#0}>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./tokio-1.32.0/src/runtime/runtime.rs:349:50
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   51: main
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at ./fedimintd/src/main.rs:21:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]:   52: call_once<fn() -> core::result::Result<(), anyhow::Error>, ()>
Jan 25 03:04:28 charlie fedimintd-start[2026788]:              at /rustc/f688dd684faca5b31b156fac2c6e0ae81fc9bc90/library/core/src/ops/function.rs:250:5
Jan 25 03:04:28 charlie fedimintd-start[2026788]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dpc** [comment]
This looks like something that was probably fixed since it was reported, and also not very actionable unless it's spotted in real situation. If it happens hopefully #4133 will make it easier to figure out indeed. Closing.
