### ISSUE TITLE
Panic in `sends_ecash_oob_highly_parallel`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4508]
Now that we use task group to join on all features, we might have stopped ignoring panics.

```
fedimint-workspace-lcov-ci> thread 'tokio-runtime-worker' panicked at modules/fedimint-mint-tests/tests/tests.rs:151:17:
fedimint-workspace-lcov-ci> assertion `left == right` failed
fedimint-workspace-lcov-ci>   left: Failed("Transaction not accepted \"The transaction had an invalid input\"")
fedimint-workspace-lcov-ci>  right: Issuing
fedimint-workspace-lcov-ci> stack backtrace:
fedimint-workspace-lcov-ci>    0: rust_begin_unwind
fedimint-workspace-lcov-ci>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
fedimint-workspace-lcov-ci>    1: core::panicking::panic_fmt
fedimint-workspace-lcov-ci>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
fedimint-workspace-lcov-ci>    2: core::panicking::assert_failed_inner
fedimint-workspace-lcov-ci>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:342:17
```

```
                let mut sub2 = sub2.into_stream();
                assert_eq!(sub2.ok().await.unwrap(), ReissueExternalNotesState::Created);
                info!("Reissuance {num_reissue} created");
                assert_eq!(sub2.ok().await.unwrap(), ReissueExternalNotesState::Issuing); <<< PANIC
                info!("Reissuance {num_reissue} accepted");
                assert_eq!(sub2.ok().await.unwrap(), ReissueExternalNotesState::Done);
                info!("Reissuance {num_reissue} finished");
```

Seems like there's some slight race somewhere?

**Comment by elsirion** [comment]
We should still never produce invalid inputs, could mean e-cash isn't selected atomically or something like that (multiple DB tx for one operation).

**Comment by dpc** [comment]
We might have ignored a panic somewhere. We'll see if it happens again.

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/actions/runs/8238524683/job/22529660699

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/actions/runs/8253963150/job/22577011302

**Comment by bradleystachurski** [comment]
https://github.com/fedimint/fedimint/actions/runs/8301545147/job/22721908642#step:6:4627

**Comment by dpc** [comment]
I guess we should disable. @bradleystachurski

**Comment by bradleystachurski** [comment]
Ha, I came back to this issue to write the same thing :smile: 

I'll get up a PR
