### ISSUE TITLE
flaky `gatewayd-integration-tests test_gateway_configuration` test

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#5001]
```
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21 2024-04-17T21:52:38.012370Z  INFO set_configuration{payload=SetConfigurationPayload { password: Some("test_password"), num_route_hints: None, routing_fees: None, network: None, per_federation_routing_fees: None }}: ln_gateway: Set GatewayConfiguration successfully.
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21 thread 'test_gateway_configuration' panicked at gateway/ln-gateway/tests/integration_tests.rs:1238:5:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21 assertion `left == right` failed
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21   left: "Configuring"
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21  right: "Running"
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21 stack backtrace:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21 2024-04-17T21:52:38.015114Z  INFO task{name="Gateway Run"}:task{name="Subscribe to intercepted HTLCs in stream"}: ln_gateway: Successfully loaded Gateway clients.
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21    0: rust_begin_unwind
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21              at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21    1: core::panicking::panic_fmt
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21              at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21    2: core::panicking::assert_failed_inner
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21              at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:342:17
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21    3: core::panicking::assert_failed
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21              at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:297:5
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21    4: {async_block#0}
fedimint-test-all-wasm32-unknown-unknown-ci> 00:04:21              at ./tests/integration_tests.rs:1238:5
```

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/actions/runs/8858117101/job/24326381251

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/actions/runs/8858328079/job/24326831730

**Comment by justinmoon** [comment]
dev call: this is disabled temporarily
