### ISSUE TITLE
Cannot initially receive small lightning payments

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#5598]
In LNv2, there are fees charged when claiming an input, due to DOS reasons. Currently, if the client cannot claim an input due to insufficient balance, the client will crash:

```rust
async fn claim_input_dyn(
        &self,
        dbtx: &mut ClientSMDatabaseTransaction<'_, '_>,
        input: InstancelessDynClientInput,
    ) -> (TransactionId, Vec<OutPoint>) {
        let instance_input = ClientInput {
            input: DynInput::from_parts(self.module_instance_id, input.input),
            keys: input.keys,
            amount: input.amount,
            state_machines: states_add_instance(self.module_instance_id, input.state_machines),
        };

        self.client
            .finalize_and_submit_transaction_inner(
                &mut dbtx.global_tx().to_ref_nc(),
                self.operation,
                TransactionBuilder::new().with_input(instance_input),
            )
            .await
            .expect("Can only fail if additional funding is needed")
    }
```
```
thread 'tokio-runtime-worker' panicked at fedimint-client/src/lib.rs:477:14:
Can only fail if additional funding is needed: Insufficient balance: requested 5 msat but only 0 msat available

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/jumoell/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/backtrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1964:27
   2: <fedimint_mint_client::SelectNotesWithAtleastAmount as fedimint_mint_client::NotesSelector<Note>>::select_notes::{{closure}}
             at ./modules/fedimint-mint-client/src/lib.rs:1725:12
   3: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   4: fedimint_mint_client::MintClientModule::select_notes::{{closure}}
             at ./modules/fedimint-mint-client/src/lib.rs:1244:14
   5: fedimint_mint_client::MintClientModule::create_sufficient_input::{{closure}}
             at ./modules/fedimint-mint-client/src/lib.rs:876:10
   6: <fedimint_mint_client::MintClientModule as fedimint_client::module::ClientModule>::create_final_inputs_and_outputs::{{closure}}
             at ./modules/fedimint-mint-client/src/lib.rs:779:14
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   8: <T as fedimint_client::module::IClientModule>::create_final_inputs_and_outputs::{{closure}}
             at ./fedimint-client/src/module/mod.rs:891:10
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  10: fedimint_client::Client::finalize_transaction::{{closure}}
             at ./fedimint-client/src/lib.rs:1032:14
  11: fedimint_client::Client::finalize_and_submit_transaction_inner::{{closure}}
             at ./fedimint-client/src/lib.rs:1130:14
  12: <fedimint_client::ModuleGlobalClientContext as fedimint_client::IGlobalClientContext>::claim_input_dyn::{{closure}}
             at ./fedimint-client/src/lib.rs:476:14
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  14: fedimint_client::DynGlobalClientContext::claim_input::{{closure}}
             at ./fedimint-client/src/lib.rs:350:10
  15: fedimint_lnv2_client::receive_sm::ReceiveStateMachine::transition_incoming_contract::{{closure}}
             at ./modules/fedimint-lnv2-client/src/receive_sm.rs:123:73
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  17: fedimint_client::sm::state::StateTransition<S>::new::{{closure}}::{{closure}}
             at ./fedimint-client/src/sm/state.rs:171:64
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  19: <alloc::vec::Vec<fedimint_client::sm::state::StateTransition<S>> as fedimint_client::sm::util::MapStateTransitions>::map::{{closure}}::{{closure}}::{{closure}}
             at ./fedimint-client/src/sm/util.rs:44:90
```

For Lightning users, it will probably be a common use case to initially receive a very small amount of sats. This should not cause the client to crash, the error (and minimum receive value) should be surfaced to the user.

Easy repro is to modify this test to receive 1000 msats: https://github.com/fedimint/fedimint/pull/5597

**Comment by m1sterc001guy** [comment]
[This PR](https://github.com/fedimint/fedimint/pull/5600) added a check for the Lightning module, but IMO we should still fix the underlying `expect` here and surface the error back to the client

**Comment by m1sterc001guy** [comment]
This issue also crashes gateways with the LNv2 module if it tries to receive a payment with no liquidity.
