### ISSUE TITLE
Caugh a worrying consensus panic

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#6155]
```
h: None, params: 2 }
2024-10-11T18:21:00.381787Z  INFO spawn{task="runway/loading"}: fm::consensus: Recovering from an in-session-shutdown units_len=539
thread 'tokio-runtime-worker' panicked at /home/dpc/lab/fedimint/fedimint/fedimint-server/src/consensus/engine.rs:421:29:
Consensus Failure: rejected item accepted by federation consensus
stack backtrace:
2024-10-11T18:21:00.390753Z DEBUG spawn{task="io-thread-peer-2"}:peer_io_thread{id=2}: fm::net::peer: Trying to reconnect our_id=PeerId(0) peer=PeerId(2) addr=fedimint://127.0.0.1:26871
```

Ooops.

I'm investigating CI flakes, and just ran into it locally. The code is not hacked or anything, very close to vanilla `master`.

**Comment by dpc** [comment]
Ping @joschisan

**Comment by dpc** [comment]
Caught it again, this time with extra panic details

```
thread 'tokio-runtime-worker' panicked at /home/dpc/lab/fedimint/fedimint/fedimint-server/src/consensus/engine.rs:421:29:
Consensus Failure: rejected item accepted by federation consensus: AcceptedItem { item: Module(DynModuleConsensusItem { id: 3, kind: Some(ModuleKind("lnv2")), inner: UnixTimeVote(172
8675433) }), peer: PeerId(0) }, items: 152+102, session_idx: 0
stack backtrace:
```

**Comment by dpc** [comment]
Another one.

```
thread 'tokio-runtime-worker' panicked at /home/dpc/lab/fedimint/fedimint/fedimint-server/src/consensus/engine.rs:421:29:
Consensus Failure: rejected item accepted by federation consensus: AcceptedItem { item: Module(DynModuleConsensusItem { id: 3, kind: Some(ModuleKind("lnv2")), inner: UnixTimeVote(1728675826) }), peer: PeerId(3) }, items: 59+139, session_idx: 1
stack backtrace:
```

**Comment by dpc** [comment]
BTW.

I'm using

```
> c b && ionice -c3 -n7 nix run nixpkgs#cpulimit -- -i -l 65 env RUST_LOG=fm=debug FM_DEVIMINT_CMD_INHERIT_STDERR=1 ./scripts/tests/reconnect-test.sh
```

to hunt for these. Artificially limiting CPU seems to trigger it quite reliably.

**Comment by dpc** [comment]
```
thread 'tokio-runtime-worker' panicked at /home/dpc/lab/fedimint/fedimint/fedimint-server/src/consensus/engine.rs:421:29:
Consensus Failure: rejected item accepted by federation consensus: AcceptedItem { item: Module(DynModuleConsensusItem { id: 3, kind: Some(ModuleKind("lnv2")), inner: UnixTimeVote(1728676903) }), peer: PeerId(1) }, items: 87+3, session_idx: 1
```

**Comment by dpc** [comment]
```
thread 'tokio-runtime-worker' panicked at /home/dpc/lab/fedimint/fedimint/fedimint-server/src/consensus/engine.rs:421:29:
Consensus Failure: rejected item accepted by federation consensus: AcceptedItem { item: Module(DynModuleConsensusItem { id: 3, kind: Some(ModuleKind("lnv2")), inner: UnixTimeVote(1728678234) }), peer: PeerId(3) }, items: 76+4, session_idx: 2, err: Item was discarded previously
```

**Comment by dpc** [comment]
```
thread 'tokio-runtime-worker' panicked at /home/dpc/lab/fedimint/fedimint/fedimint-server/src/consensus/engine.rs:421:29:
Consensus Failure: rejected item accepted by federation consensus: AcceptedItem { item: Module(DynModuleConsensusItem { id: 3, kind: Some(ModuleKind("lnv2")), inner: UnixTimeVote(1728679466) }), peer: PeerId(3) }, items: 172+100, session_idx: 0, err: Item was discarded previously: existing: AcceptedItem { item: Module(DynModuleConsensusItem { id: 2, kind: Some(ModuleKind("wallet")), inner: BlockCount(92) }), peer: PeerId(0) } 0, current: Module(DynModuleConsensusItem { id: 3, kind: Some(ModuleKind("lnv2")), inner: UnixTimeVote(1728679466) }), 3
```


Hmmm...

**Comment by dpc** [comment]
```
                    for accepted_item in unprocessed {
                        if let Err(err) = self.process_consensus_item(
                            session_index,
                            item_index,
                            accepted_item.item.clone(),
                            accepted_item.peer
                        ).await {
```

Processing  only `unprocessed` items, but with `item_index` that belong to the outter-loop and is initialized to `0` looks sus.

**Comment by joschisan** [comment]
This should fix it: https://github.com/fedimint/fedimint/pull/6166

Could you test if it does?
