### ISSUE TITLE
lnv2-module-test flaky

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#6466]
https://github.com/fedimint/fedimint/actions/runs/12038319600/job/33563730945

```
 fedimint-test-all-wasm32-unknown-unknown-ci> 00:01:54 thread 'main' panicked at modules/fedimint-lnv2-tests/src/bin/tests.rs:358:5:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:01:54 assertion `left == right` failed
fedimint-test-all-wasm32-unknown-unknown-ci> 00:01:54   left: String("Refunded")
fedimint-test-all-wasm32-unknown-unknown-ci> 00:01:54  right: String("Success")
fedimint-test-all-wasm32-unknown-unknown-ci> 00:01:54 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dpc** [comment]
@fedimint/lightning

**Comment by dpc** [comment]
After running

```
env FM_DEVIMINT_CMD_INHERIT_STDERR=1 RUST_LOG=fm=debug retry-success.sh ionice -c2 -n7 nix run nixpkgs#cpulimit -- -i -l 125 ./scripts/tests/lnv2-module-test.sh
```

I was eventually able to hit:

```
2024-11-26T21:50:24.310860Z DEBUG fm::devimint: Sending funds from bitcoind amount=1001000 addr="bcrt1q7cwdv5jhtlxllyeh4r6hf5e35vtgwja4xj7xt58jag8efrsw9r
kqhz2ws7"
2024-11-26T21:50:25.431691Z DEBUG fm::devimint: Mining bitcoin blocks block_num=21
2024-11-26T21:50:26.104251Z DEBUG fm::devimint: Mined blocks elapsed_ms=672 block_num=21
2024-11-26T21:50:26.104346Z DEBUG fm::devimint: > gateway-cli --rpcpassword=theresnosecondbest -a http://127.0.0.1:11575/v1 get-balances
2024-11-26T21:50:26.104718Z DEBUG fm::devimint: > gateway-cli --rpcpassword=theresnosecondbest -a http://127.0.0.1:11576/v1 get-balances
2024-11-26T21:50:26.438382Z DEBUG fm::devimint: Polling gateway pegin failed, will retry... attempt=0 err=assertion failed, left: 0 right: 1000000000

...

Error: Polling gateway pegin failed after 32 retries (timeout: 60s)

Caused by:
    assertion failed, left: 0 right: 1000000000
```

In the `/tmp/devimint-3413586-199/logs/gatewayd-ldk.log` I see:

```
2024-11-26T21:51:33.000020Z  INFO spawn{task="kill handlers"}: fm::task: signal received, starting graceful shutdown
2024-11-26T21:51:33.000102Z  INFO spawn{task="Subscribe to intercepted lightning payments in stream"}: ln_gateway: Received shutdown signal
2024-11-26T21:51:33.000116Z  INFO spawn{task="Subscribe to intercepted lightning payments in stream"}: ln_gateway::lightning::ldk: Stopping LDK Node...
2024-11-26T21:51:33.000252Z  INFO spawn{task="Gateway Webserver"}: ln_gateway::rpc::rpc_server: Successfully shutdown webserver
2024-11-26T21:51:33.000813Z  INFO spawn{task="Subscribe to intercepted lightning payments in stream"}: ln_gateway::lightning::ldk: LDK Node stopped.
thread 'main' panicked at /home/dpc/lab/fedimint/fedimint/gateway/ln-gateway/src/federation_manager.rs:160:22:
Must have client module: No modules found of kind ln

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.93/src/backtrace.rs:27:14
   1: anyhow::__private::format_err
             at /home/dpc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.93/src/lib.rs:694:13
   2: fedimint_client::Client::get_first_module::{{closure}}
             at ./fedimint-client/src/lib.rs:1383:28
   3: core::option::Option<T>::ok_or_else
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:1269:25
   4: fedimint_client::Client::get_first_module
             at ./fedimint-client/src/lib.rs:1381:18
   5: ln_gateway::federation_manager::FederationManager::unannounce_from_all_federations::{{closure}}::{{closure}}::{{closure}}
```

**Comment by dpc** [comment]
Oh, it was a peg-in that failed. So I can see that it was monitoring it:

```
2024-11-26T21:50:33.189131Z DEBUG spawn{task="peg-in monitor"}:check_idx_pegins: fm::client::module::wallet: Got history of a peg-in address address=bcrt1q7cwdv5jhtlxllyeh4r6hf5e35vtgwja4xj7xt58jag8efrsw9rkqhz2ws7 num_txes=0
2024-11-26T21:50:33.300370Z DEBUG spawn{task="peg-in monitor"}: fm::timing: Operation timing name=autocommit - commit_tx duration_ms=0
2024-11-26T21:50:33.300429Z DEBUG spawn{task="peg-in monitor"}: fm::client::module::wallet: Sleep after completing due checks sleep_secs=0
2024-11-26T21:50:33.412835Z DEBUG spawn{task="peg-in monitor"}: fm::client::module::wallet: Woken up by a scheduled wakeup
2024-11-26T21:50:33.525677Z DEBUG spawn{task="peg-in monitor"}:check_idx_pegins: fm::client::module::wallet: Got history of a peg-in address address=bcrt1q7cwdv5jhtlxllyeh4r6hf5e35vtgwja4xj7xt58jag8efrsw9rkqhz2ws7 num_txes=1
2024-11-26T21:50:33.637168Z DEBUG spawn{task="peg-in monitor"}:check_idx_pegins: fm::client::module::wallet: Needs more confirmations txid=758766d99e195188618aeb0623b8c5f2cfee7f3e2aaad723ffc3fa9439de5cab out_idx=1 num_blocks_needed=11 finality_delay=10 tx_block_count=174 current_consensus_block_count=163
2024-11-26T21:50:33.637417Z DEBUG spawn{task="peg-in monitor"}: fm::timing: Operation timing name=autocommit - commit_tx duration_ms=0

...

2024-11-26T21:51:02.088742Z DEBUG spawn{task="peg-in monitor"}:check_idx_pegins: fm::client::module::wallet: Got history of a peg-in address address=bcrt1q7cwdv5jhtlxllyeh4r6hf5e35vtgwja4xj7xt58jag8efrsw9rkqhz2ws7 num_txes=1
2024-11-26T21:51:02.539342Z DEBUG spawn{task="peg-in monitor"}:check_idx_pegins: fm::client::module::wallet: Ready to claim txid=758766d99e195188618aeb06
23b8c5f2cfee7f3e2aaad723ffc3fa9439de5cab out_idx=1 finality_delay=10 tx_block_count=174 current_consensus_block_count=184
2024-11-26T21:51:02.991362Z DEBUG spawn{task="peg-in monitor"}:check_idx_pegins: fm::client::module::wallet: Claiming a peg-in out_point=758766d99e195188
618aeb0623b8c5f2cfee7f3e2aaad723ffc3fa9439de5cab:1
```

**Comment by dpc** [comment]
It seems like the cpulimit I've used was just too tight. The original issue is probably legit, but I still need to repro locally.

**Comment by dpc** [comment]
OK. I was able to repro by running a lot of 

```
c b --all-targets && env FM_DEVIMINT_CMD_INHERIT_STDERR=1 RUST_LOG=fm=debug retry-success.sh ionice -c2 -n7 nix run nixpkgs#cpulimit -- -i -l 175 ./scripts/tests/lnv2-module-test.sh
```

and eventually one of them failed the way it failed in the CI.

I have captured the output and the tmp directory and sent them on Discord to @joschisan @m1sterc001guy as I might not be able to debug it anytime soon.

**Comment by dpc** [comment]
Looks to me like the payment just ... failed immediately in LDK. We probably need better logging to figure out why exactly.


```
2024-11-27T01:22:01.416200Z DEBUG spawn{task="sm-executor"}:sm_transition{operation_id=a72d289c_2c5ce18b}: fm::client::reactor: State transition complete termi
nal=true outcome=Inactive { dyn_state: Send(SendStateMachine { common: SendSMCommon { operation_id: OperationId(a72d289c_2c5ce18b), contract: OutgoingContract
{ payment_image: Hash(0x1df86ac98f7b2023b44b3332c915c7a1dcda1836256e9e0874eae03e0debf305), amount: Amount { msats: 1115000 }, expiration: 1646, claim_pk: Publi
cKey(d1748b3b815e640ed1674d03e446c7d4dbd94602bdc5bf98e82798656ba2a40df48a0bd03e6249042311c170492661744b65eaa4adba34fe26c94e0d568afb17), refund_pk: PublicKey(f7
f996f0686df4adf87e02f913e1a3f42dd57879ec118e0e5ca438cb0fa39407fc45a4c0f696d5297d887c42eabd4a021fcb8aaed4f299d82ea225b0ea2d8461), ephemeral_pk: PublicKey(e0ad86
3089947f6235b71cd19a65018a6bf49de46f8b709babf719121076da57fa0770e3cdae606e3278cd6b99e5b0172e01e57e0cd01f521d78a8dea8fbc516) }, max_delay: 1308, min_contract_am
ount: Amount { msats: 1055000 }, invoice: Bolt11(Bolt11Invoice { signed_invoice: SignedRawBolt11Invoice { raw_invoice: RawBolt11Invoice { hrp: RawHrp { currenc
y: Regtest, raw_amount: Some(10), si_prefix: Some(Micro) }, data: RawDataPart { timestamp: PositiveTimestamp(1732670520s), tagged_fields: [KnownSemantics(Payme
ntHash(Sha256(0x1df86ac98f7b2023b44b3332c915c7a1dcda1836256e9e0874eae03e0debf305))), KnownSemantics(Description(Description(UntrustedString("")))), KnownSemant
ics(MinFinalCltvExpiryDelta(MinFinalCltvExpiryDelta(80))), KnownSemantics(ExpiryTime(ExpiryTime(3600s))), KnownSemantics(PaymentSecret(3f18dd7ddd11e66db1baafea
ab889ebfc0e35b547ce73ae0838c9894cc2ba2d2)), KnownSemantics(Features([0, 66, 2]))] } }, hash: [181, 32, 173, 65, 149, 245, 234, 174, 245, 105, 144, 225, 131, 10
7, 65, 195, 117, 95, 129, 177, 167, 97, 88, 137, 107, 88, 220, 250, 161, 128, 67, 67], signature: Bolt11InvoiceSignature(RecoverableSignature(9edf2c696c7872bba
55b3d963f2536962d5537594f755fca56a841c204e6b96f2a58d748b2cee0b4a9146876c2e029d54f4996c91a2f1e5fa62628b64851382400)) } }), claim_keypair: Keypair(#fe98d9de4c450
e95) }, state: Cancelled(LightningRpcError("Payment failed: LDK payment failed")) }) }
2024-11-27T01:22:01.416286Z DEBUG spawn{task="sm-executor"}: fm::client::reactor: State transition complete operation_id=a72d289c_2c5ce18b outcome_active=false
 total=0
2024-11-27T01:22:01.416318Z  WARN pay_bolt11_invoice_v2: ln_gateway::gateway_module_v2: Outgoing lightning payment is cancelled LightningRpcError("Payment fail
ed: LDK payment failed")
```

**Comment by dpc** [comment]
Missed LDK logs

```
2024-11-27 01:22:01 DEBUG [lightning::ln::channel:5138] Received a valid revoke_and_ack for channel 7386d4892adf82550373ad92d6eab46ba27b7ee204f035d2d30ea6edc34fcf0a with no reply necessary. R
eleasing monitor update.
2024-11-27 01:22:01 INFO  [lightning::chain::channelmonitor:3088] Applying update to monitor 7386d4892adf82550373ad92d6eab46ba27b7ee204f035d2d30ea6edc34fcf0a, bringing update_id from 19 to 20
 with 1 change(s).
2024-11-27 01:22:01 DEBUG [lightning::chain::chainmonitor:842] Persistence of ChannelMonitorUpdate id 20 for channel 7386d4892adf82550373ad92d6eab46ba27b7ee204f035d2d30ea6edc34fcf0a completed
2024-11-27 01:22:01 DEBUG [lightning::ln::channel:5416] Restored monitor updating in channel 7386d4892adf82550373ad92d6eab46ba27b7ee204f035d2d30ea6edc34fcf0a resulting in no commitment update and no RAA, with RAA first
2024-11-27 01:22:01 INFO  [lightning::ln::onion_utils:865] Onion Error[from 02a930997533c0333c2ca89f165913ebdb4566f0b8ef96ce9eed526da3b0eecaf8: incorrect_or_unknown_payment_details(0x400f)] The final node indicated the payment hash is unknown or amount is incorrect
2024-11-27 01:22:01 DEBUG [lightning::routing::scoring:1403] Not able to penalize channel with SCID 134140418654208 as we do not have graph info for it (likely a route-hint last-hop).
2024-11-27 01:22:01 INFO  [ldk_node::event:885] Failed to send payment with ID 1df86ac98f7b2023b44b3332c915c7a1dcda1836256e9e0874eae03e0debf305 due to Some(RecipientRejected).
2024-11-27 01:22:03 DEBUG [lightning::ln::channelmanager:10371] Marking channels with 02a930997533c0333c2ca89f165913ebdb4566f0b8ef96ce9eed526da3b0eecaf8 disconnected and generating channel_updates.
```
