### ISSUE TITLE
flaky sends_ecash_out_of_band_cancel

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#6526]
https://github.com/fedimint/fedimint/actions/runs/12225472980/job/34099487285

```
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36 thread 'sends_ecash_out_of_band_cancel' panicked at modules/fedimint-mint-tests/tests/tests.rs:368:5:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36 assertion `left == right` failed
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36   left: Refunded
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36  right: UserCanceledProcessing
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36 stack backtrace:
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36    0: rust_begin_unwind
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36    1: core::panicking::panic_fmt
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36    2: core::panicking::assert_failed_inner
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:412:17
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36    3: core::panicking::assert_failed
fedimint-test-all-wasm32-unknown-unknown-ci> 00:00:36              at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:367:5
```

**Comment by elsirion** [comment]
Are we still seeing this?

**Comment by dpc** [comment]
I don't think we do.
